spring:
  jpa:
    properties:
      hibernate:
        format_sql: true

    defer-datasource-initialization: true
    show-sql: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true